### ISSUE TITLE
Add documentation regarding Themes (.sublime-theme)

### ISSUE THREAD

**Issue by pradyunsg** [guillermooo/sublime-undocs#176]
Firstly, Thanks for maintaining such awesome documentation. It's been a great resource.

Currently, Themes are not documented. There is no mention of ".sublime-theme" in the entire documentation.

(now I have no idea what to write)
Please document the same.

**Comment by FichteFoll** [comment]
That's not true. `.sublime-theme` files are mentioned as possible resource files: http://docs.sublimetext.info/en/latest/extensibility/packages.html#package-contents

But I know what you mean. We didn't have documentation on color schemes either just a while ago, and we are currently working on documentation for menus. After that, I'll most likely add some docs for mouse bindings because it's a rather small topic (compared to themes at least).

The problem with themes is that neither I nor @guillermooo have ever done something with them, meaning we would have to work into it entirely before being able to write documentation for it. But fear not, it's on our roadmap.

**Comment by pradyunsg** [comment]
@FichteFoll In my defense, it didn't show up in the search ".sublime-theme".

@buymeasoda Could you please consider doing this?

**Comment by pradyunsg** [comment]
PS: Where is your roadmap?

**Comment by FichteFoll** [comment]
https://trello.com/b/ArLlY4X7/sublime-text-unofficial-documentation (as linked in the readme)

That one's not complete, however. We also keep an internal roadmap for things we haven't clearly decided on yet (theming falls into that list) or are generally uninteresting for others.

**Comment by keith-hall** [comment]
There is now official documentation on themes at http://www.sublimetext.com/docs/3/themes.html

**Comment by pradyunsg** [comment]
Closing then.
